# Generated by Django 4.0.2 on 2022-02-07 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_activity_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossTrain',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.activity')),
            ],
            bases=('planner.activity',),
        ),
        migrations.CreateModel(
            name='Intervals',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.activity')),
                ('rep_length', models.PositiveSmallIntegerField()),
                ('rep_number', models.PositiveSmallIntegerField()),
                ('reps_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prog_reps', models.PositiveSmallIntegerField(default=1)),
            ],
            bases=('planner.activity',),
        ),
        migrations.CreateModel(
            name='PacedRun',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.activity')),
                ('prog_value', models.CharField(choices=[('TIME', 'Time(minutes)'), ('DIST', 'Distance(km)')], default='TIME', max_length=4)),
                ('prog_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prog_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pace', models.CharField(choices=[('WALK', 'Walk'), ('JOG', 'Easy Jog'), ('MED', 'Moderate Run'), ('HARD', 'Challenging Run'), ('MAX', 'Maximum Effort')], default='HARD', max_length=4)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(720)])),
                ('goal_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(720)])),
                ('goal_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            bases=('planner.activity',),
        ),
        migrations.CreateModel(
            name='TimeTrial',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.activity')),
                ('time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goal_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prog_time', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            bases=('planner.activity',),
        ),
        migrations.AddField(
            model_name='activity',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='last_done',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='progressive',
            field=models.BooleanField(default=False),
        ),
    ]
