# Generated by Django 4.0.2 on 2022-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_crosstrain_intervals_pacedrun_timetrial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosstrain',
            name='exercise_type',
            field=models.CharField(default='Training', max_length=30),
        ),
    ]
