# Generated by Django 4.0.2 on 2022-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_crosstrain_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='namenlose', max_length=40),
        ),
        migrations.AlterField(
            model_name='crosstrain',
            name='exercise_type',
            field=models.CharField(default='Cross Training', max_length=30),
        ),
        migrations.AlterField(
            model_name='pacedrun',
            name='pace',
            field=models.CharField(choices=[('WALK', 'Walk'), ('JOG', 'Easy Jog'), ('MED', 'Moderate Run'), ('HARD', 'Hard Run'), ('MAX', 'Maximum Effort')], default='MED', max_length=4),
        ),
    ]
