# Generated by Django 4.0.2 on 2022-02-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_activity_name_alter_crosstrain_exercise_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacedrun',
            name='pace',
            field=models.CharField(choices=[('walk', 'Walk'), ('jog', 'Easy Jog'), ('moderate run', 'Moderate Run'), ('hard run', 'Hard Run'), ('maximum effort run', 'Maximum Effort')], default='moderate run', max_length=18),
        ),
    ]
