# Generated by Django 4.0.2 on 2022-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_pacedrun_pace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacedrun',
            name='prog_value',
            field=models.CharField(choices=[('TIME', 'Time(minutes)'), ('DIST', 'Distance(km)')], default='Time(minutes)', max_length=4),
        ),
    ]
