# Generated by Django 4.0.2 on 2022-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_pacedrun_prog_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacedrun',
            name='pace',
            field=models.CharField(choices=[('Walk', 'Walk'), ('Jog', 'Easy Jog'), ('Moderate Run', 'Moderate Run'), ('Hard Run', 'Hard Run'), ('Maximum Effort', 'Maximum Effort')], default='Moderate Run', max_length=18),
        ),
    ]
