# Generated by Django 4.0.2 on 2022-02-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_activity_my_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervals',
            old_name='prog_reps',
            new_name='increment',
        ),
        migrations.RenameField(
            model_name='intervals',
            old_name='reps_goal',
            new_name='rep_goal',
        ),
    ]
