# Generated by Django 4.0.2 on 2022-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_rename_prog_reps_intervals_increment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Hard')], default='2', max_length=1),
        ),
    ]
