# Generated by Django 4.0.2 on 2022-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_exercise',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.JSONField(null=True),
        ),
    ]
