# Generated by Django 4.0.2 on 2022-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_profile_last_exercise_profile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_day',
            field=models.CharField(default='Monday', max_length=8),
        ),
    ]
