# Generated by Django 4.0.2 on 2022-02-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_profile_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thrusday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
