# Generated by Django 4.0.2 on 2022-02-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_alter_profile_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mileage_increment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='mileage_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
