# Generated by Django 4.0.2 on 2022-02-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thrusday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
