# Generated by Django 4.0.2 on 2022-03-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_profile_schedule_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='frequency',
        ),
    ]
