# Generated by Django 4.0.2 on 2022-04-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_profile_schedule_init_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='start_day',
        ),
    ]
