# Generated by Django 4.0.2 on 2022-04-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_remove_profile_start_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='schedule',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='schedule_length',
            new_name='plan_length',
        ),
    ]
