# Generated by Django 4.0.2 on 2022-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_completedact_distance_alter_pacedrun_prog_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_week_initial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
