# Generated by Django 4.0.2 on 2022-05-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_remove_profile_last_exercise_remove_profile_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mileage_increment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mileage_target',
        ),
    ]
