# Generated by Django 4.0.2 on 2022-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_remove_profile_wtd_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mileage_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
