# Generated by Django 4.0.2 on 2022-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0036_profile_mileage_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_week_initial',
        ),
        migrations.AddField(
            model_name='activity',
            name='targetstring',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='nameless', max_length=40),
        ),
        migrations.AlterField(
            model_name='completedact',
            name='name',
            field=models.CharField(default='nameless', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='schedule_init_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
