# Generated by Django 4.0.2 on 2022-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0037_remove_profile_current_week_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrial',
            name='best',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
