# Generated by Django 4.0.2 on 2022-06-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0038_timetrial_best'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='targetstring',
            new_name='infostring',
        ),
    ]
