# Generated by Django 4.0.2 on 2022-06-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0039_rename_targetstring_activity_infostring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetrial',
            name='goal_time',
        ),
        migrations.RemoveField(
            model_name='timetrial',
            name='prog_time',
        ),
        migrations.RemoveField(
            model_name='timetrial',
            name='time',
        ),
    ]
