# Generated by Django 4.0.2 on 2022-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0040_remove_timetrial_goal_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pace_0',
            field=models.DecimalField(decimal_places=2, default=6.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='pace_1',
            field=models.DecimalField(decimal_places=2, default=9.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='pace_2',
            field=models.DecimalField(decimal_places=2, default=10.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='pace_3',
            field=models.DecimalField(decimal_places=2, default=11.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='pace_4',
            field=models.DecimalField(decimal_places=2, default=13.5, max_digits=4),
        ),
    ]
